site_name: Studio Templates
site_url: https://caio-skyone.github.io/studio-templates/
exclude_docs: |
  superpowers/
theme:
  name: material
  palette:
    scheme: slate
  favicon: img/favicon.svg
  logo: img/logo.svg
plugins:
- roamlinks
hooks:
- hooks/iac_assets.py
nav:
- Início: index.md
- Conectores:
  - Databricks: connectors/databricks.md
  - GitHub: connectors/github.md
  - iFood: connectors/ifood.md
  - Jira: connectors/jira.md
  - Mailgun: connectors/mailgun.md
  - Notion: connectors/notion.md
  - Service Now: connectors/service-now.md
  - Stripe: connectors/stripe.md
  - Twilio: connectors/twilio.md
  - Xero: connectors/xero.md
  - Zendesk: connectors/zendesk.md
  - Zoho Books: connectors/zoho-books.md
  - Zoho CRM: connectors/zoho-crm.md
  - Zoho Desk: connectors/zoho-desk.md
  - Zoho Projects: connectors/zoho-projects.md
- Fluxo de Desenvolvimento:
  - Callback OAuth2:
    - Contexto: dev-flow/callback/contexto.md
    - Postman: dev-flow/callback/oauth2postman.md
- IAC: iac-viewer.md
